### ISSUE TITLE
typed text isn't visible (need a way to select dark-background or light-background palettes)

### ISSUE THREAD

**Issue by yurivict** [xo/usql#36] opened 2018-02-25 09:35 UTC
The typed text "help" below wasn't visible in the terminal.
```
$ usql sqlite:/var/db/pkg/local.sqlite
Connected with driver sqlite3 (SQLite3 3.21.0)
Type "help" for help.

sq:/var/db/pkg/local.sqlite=> help
You are using usql, the universal command-line interface for SQL databases.
Type:  \copyright for distribution terms
       \? for help with usql commands
       \g or terminate with semicolon to execute query
       \q to quit
sq:/var/db/pkg/local.sqlite=>  
```

**Comment by kenshaw** [comment] 2018-02-25 23:39
Could you provide more information about your environment? Operating system, etc.? Were you using one of the release binaries?

I would likely guess it has something to do with the syntax highlighting. You can try disabling the syntax highlighting by doing the following:

```sh
$ usql
Type "help" for help.

(not connected)=> \set SYNTAX_HL false
(not connected)=>
```
If this fixes your issue, then the problem is likely that package `usql` uses to detect the color output isn't working as expected. Try the above and let me know if that "fixes" the issue -- if so, please copy and paste your terminal's environment variables:

```sh
$ env
```

**Comment by yurivict** [comment] 2018-02-25 23:46
FreeBSD 11.1
Built while was creating a port. No binaries, ever.

This
> (not connected)=> \set SYNTAX_HL false

didn't help.

**Comment by kenshaw** [comment] 2018-02-25 23:48
You're seeing output, but not syntax colored output? For example, the `(not connected) =>` prompt is visible?

**Comment by yurivict** [comment] 2018-02-25 23:49
> (not connected) => prompt is visible?

Yes. But when I type text it isn't visible. However, "\set SYNTAX_HL false" was visible.

**Comment by kenshaw** [comment] 2018-02-25 23:51
I can't think of any other causes of this kind of behavior, other than the syntax highlighting. Could you output your environment variables? What shell / tty are you using? Do you have similar problems in other applications (not necessarily ones written in Go, as I'm guessing that `usql`'s implementation is unique).

**Comment by yurivict** [comment] 2018-02-25 23:53
Environment:
```
$ env
XDG_MENU_PREFIX=xfce-
DISPLAY=unix:0.0
COLORTERM=truecolor
CVSROOT=/usr/home/cvs
SSH_AUTH_SOCK=/tmp/ssh-aIOD9VFrJeLp/agent.4362
GLADE_CATALOG_PATH=:
USER=yuri
GLADE_MODULE_PATH=:
DESKTOP_SESSION=xfce
PWD=/usr/ports
HOME=/home/yuri
LC_CTYPE=en_US.UTF-8
SSH_AGENT_PID=4363
CLICOLOR=1
XDG_DATA_DIRS=/usr/local/share:/usr/share
SVN_EDITOR=vim
GLADE_PIXMAP_PATH=:
MAIL=/var/mail/yuri
TERM=xterm-256color
SHELL=/usr/local/bin/bash
VTE_VERSION=4803
QT_IM_MODULE=ibus
XMODIFIERS=@im=ibus
XDG_CURRENT_DESKTOP=XFCE
SHLVL=1
WINDOWID=37748739
LOGNAME=yuri
DBUS_SESSION_BUS_ADDRESS=unix:path=/tmp/dbus-mFZSubmAhO,guid=69f8e988663a552b9c91a3e45a93201f
XDG_RUNTIME_DIR=/var/run/user/1001
XAUTHORITY=/home/yuri/.Xauthority
XFCE4_SESSION_WITH_CK=1
XDG_CONFIG_DIRS=/etc/xdg:/usr/local/etc/xdg
PATH=.:/home/yuri/bin:/sbin:/bin:/usr/sbin:/usr/bin:/usr/local/sbin:/usr/local/bin
XDG_SESSION_COOKIE=xx.xxxxxx.xx-1519591454.955511-1913274999
SESSION_MANAGER=local/yv.noip.me:/tmp/.ICE-unix/4374
GTK_IM_MODULE=ibus
_=/usr/bin/env
```

Shell: bash
Terminal: xfce4-terminal
Never saw such problem anywhere else.

**Comment by kenshaw** [comment] 2018-02-26 00:04
If you're building it from source for a port I would recommend using `dep` to lock the built dependencies into place.

**Comment by yurivict** [comment] 2018-02-26 00:08
I can't use ```dep```, port locks them explicitly.
```
GH_TUPLE=       xo:dburl:2406b5c:dburl/src/github.com/xo/dburl \
                xo:terminfo:b44407a:terminfo/src/github.com/xo/terminfo \
                xo:xoutil:46189f4:xoutil/src/github.com/xo/xoutil \
                alecthomas:chroma:v0.3.0:chroma/src/github.com/alecthomas/chroma \
                alexflint:go-arg:0cc8e30:goarg/src/github.com/alexflint/go-arg \
                danwakefield:fnmatch:cbb64ac:fnmatch/src/github.com/danwakefield/fnmatch \
                denisenkom:go-mssqldb:ee49270:gomssqldb/src/github.com/denisenkom/go-mssqldb \
                dlclark:regexp2:v1.1.6:regexp2/src/github.com/dlclark/regexp2 \
                go-sql-driver:mysql:v1.3:mysql/src/github.com/go-sql-driver/mysql \
                gohxs:readline:a780388:readline/src/github.com/gohxs/readline \
                lib:pq:88edab0:pq/src/github.com/lib/pq \
                mattn:go-isatty:v0.0.3:goisatty/src/github.com/mattn/go-isatty \
                mattn:go-runewidth:v0.0.2:gorunewidth/src/github.com/mattn/go-runewidth \
                mattn:go-sqlite3:v1.6.0:gosqlite3/src/github.com/mattn/go-sqlite3 \
                olekukonko:tablewriter:b8a9be0:tablewriter/src/github.com/olekukonko/tablewriter \
                zaf:temp:94e3859:temp/src/github.com/zaf/temp \
                golang:crypto:650f4a3:crypto/src/golang.org/x/crypto
```

**Comment by kenshaw** [comment] 2018-02-26 00:11
I just started FreeBSD 11.1 in VirtualBox (no X installed), and tested usql from the command line. Colors work: so this is some kind of logic / terminal detection issue. I manually set the syntax highlighting parameters, however. If you could try the same and report back, I'd appreciate it. Could you try it outside of X?

![screenshot from 2018-02-26 07-09-24](https://user-images.githubusercontent.com/2274859/36648302-32622302-1ac4-11e8-806f-f1d4ce35dd65.png)

**Comment by kenshaw** [comment] 2018-02-26 00:32
If `help` is being highlighted, then syntax highlighting is working properly. `usql` uses github.com/alecthomas/chroma for the coloring; you can set the theme through `\set SYNTAX_HL_STYLE <name>` where `<name>` is one of the styles available in `chroma`. The list of `chroma` style names available for use can be retrieved via the `chroma` cli tool: 

```sh
$ go get -u github.com/alecthomas/chroma/cmd/chroma
$ chroma --list
...
styles: abap algol algol_nu arduino autumn borland bw colorful dracula emacs friendly fruity github igor lovelace manni monokai monokailight murphy native paraiso-dark paraiso-light pastie perldoc pygments rainbow_dash rrt swapoff tango trac vim vs xcode
...
```

Any of the named styles above can be used in conjunction with `\set SYNTAX_HL_STYLE`. If you'd like to set these settings all the time, you can put them in your `.usqlrc` file. 

Additionally, you may execute `\set` in `usql` without any parameters to see what the current syntax settings are:

```sh
$ usql
(not connected) => \set 
SHOW_HOST_INFORMATION = 'true'
SYNTAX_HL = 'true'
SYNTAX_HL_FORMAT = 'terminal16m'
SYNTAX_HL_OVERRIDE_BG = 'true'
SYNTAX_HL_STYLE = 'monokai'
(not connected)=>
```
If you set `SYNTAX_HL` to any other value than `true`, it will disable syntax highlighting.

`SYNTAX_HL_STYLE` may be set to any of the named styles from `chroma` (see above).

When `SYNTAX_HL_OVERRIDE_BG` is any other value than `true`, `usql` will not "erase" the background components from the named `chroma` style -- this is the default because *most* of the `chroma` styles have background colors, and they rarely look correct in most cases (from what I've seen).

`SYNTAX_HL_FORMAT` can be any of the `chroma` named formatters. For best results, do not use anything other than the following `chroma` formatters: `noop terminal terminal256 terminal16m`. These formatters produce "no coloring", "16 colors", "256 colors", and "millions of colors", respectively.

**Comment by kenshaw** [comment] 2018-02-26 00:35
I would recommend trying either the `dracula` (white backgrounds) or `monokai` (dark backgrounds) styles.

For reference, on my main development machine, `usql`'s colored syntax highlighting looks like the attached screenshot.
![screenshot from 2018-02-26 07-33-43](https://user-images.githubusercontent.com/2274859/36648552-8a8c0dc4-1ac7-11e8-8857-b1b6d4285df3.png)

**Comment by yurivict** [comment] 2018-02-26 00:49
For some reason, I still have the same problem with 'dracula':

```
(not connected)=> \set
SHOW_HOST_INFORMATION = 'true'
SYNTAX_HL = 'true'
SYNTAX_HL_FORMAT = 'terminal16m'
SYNTAX_HL_OVERRIDE_BG = 'true'
SYNTAX_HL_STYLE = 'dracula'
TIME_FORMAT = '2006-01-02T15:04:05.999999999Z07:00'
```

**Comment by kenshaw** [comment] 2018-02-26 00:50
Could you upload a screenshot so that I can see what you're seeing? Additionally, have you tried using it in a regular tty?

**Comment by yurivict** [comment] 2018-02-26 21:03
Here's how I see it in the xfce4 terminal:

![usql-colors](https://user-images.githubusercontent.com/271906/36695128-3574d504-1af5-11e8-8527-143730481ac9.png)

I will tell you about the system terminal later.

**Comment by kenshaw** [comment] 2018-02-27 00:36
Please try typing in a regular SQL query as well, and see if it comes back with more visible colors. I would also suggest changing your terminal settings to be white on black or black on white. The highlighting definitely is working, it just seems to be faint. I'd suggest trying all the other styles supported by `chroma` until you find one that works with your terminal's color settings.

**Comment by kenshaw** [comment] 2018-03-10 01:56
Closing this, as more input would be needed from the @yurivict in order to fix this -- "it works for me."

**Closed by kenshaw** 2018-03-10 01:56 UTC
