### ISSUE TITLE
Add tab-completion

### ISSUE THREAD

**Issue by glensc** [xo/usql#182] opened 2021-03-05 10:53 UTC
```
➔ usql
Type "help" for help.

(not connected)=> help
You are using usql, the universal command-line interface for SQL databases.
Type:  \copyright for distribution terms
       \? for help with usql commands
       \g or terminate with semicolon to execute query
       \q to quit
(not connected)=> \cop    _
```

I typed `\cop` and then pressed `\t`, I would expect it to be expanded to `\copyright` not insert literal tab.

**Comment by nineinchnick** [comment] 2021-03-05 12:23
Duplicate of #150 and #41

**Closed** 2021-03-05 12:37 UTC
