### ISSUE TITLE
What is necessary to be able to implement completion?

### ISSUE THREAD

**Issue by thalesmello** [xo/usql#31] opened 2017-10-05 19:26 UTC
Hello.

I just recently came to this project, and I found it to be very interesting.

I'm looking forward to the Autocomplete feature, and I intend contributing to the project to implement it.

What would be the general guidelines to have something like this implemented?

**Comment by kenshaw** [comment] 2017-10-06 09:07
I'm not sure if you're asking what it would take to implement it, what my policy would be on you implementing it directly, or something else. I'll try to answer everything:

1) To implement this, basically a full on SQL lexer / parser would need to be implemented. Since the different dialects of SQL are in use for the different databases, likely a "single lexer" would not be good enough. A lexer/parser would be necessary in order to create suggestions that are context sensitive (ie, there is some kind of "comprehension" of what valid/invalid SQL is.

2) Assuming that 1 is implemented, then it would be relatively easy to integrate it into the existing `readline` package that is in use in order to suggest the next item. I believe it's just a simple anonymous function that gets passed somewhere when creating the `readline` configuration. It handles the busy work of responding to tabs/completing the actual word(s).

3) If you wanted the context completion to be really cool, it would also be necessary to do some kind of database introspection for column, table names, stored proc names, etc. You might want to look at the `xo` project for some fairly comprehensive introspection code.

That said, my policy would be if you implemented any / or part of the above (or integrated some other code) I'd be glad to merge it so long as it wasn't in conflict with the MIT license. I'd be happy to merge all or part of the above for one or more databases so long as the code is well written, documented, and clear. Try using the `gometalinter` tool. This project isn't very big, so we don't have anything like crazy CLAs or anything to submit code. Just create a PR, I'll review, and either merge or close it out without merging.

Anyway, I'm glad you like the tool! I'd love to see third-party contributions!

**Comment by kenshaw** [comment] 2017-10-06 09:11
Also -- note that if you have some other clever way of doing completion without a full fledged SQL lexer/parser, that's cool too. Submit it here! If you're concerned that your work would be in vain because I disagree with your approach, do a simple 1 or 2 paragraph write-up in advance describing how you propose to implement it, and I'll provide feedback. Even if we might disagree, it's MIT licensed, so anyone is free to branch the repository -- one of the great things of open source!

**Comment by hexasoftware** [comment] 2017-10-09 07:15
Hi, 
funny 7 Months ago, I mentioned (as stdiopt) i was working in something similar with basic highlighting 

https://www.reddit.com/r/golang/comments/5x7hr4/usql_is_a_universal_commandline_for_sql_databases/

but basically I stopped working on it and lately I've been resuming testing few things including maintaining the chzyer readline, which seems dormant, in a fork project and one added feature was the ability to alter the prompt "render"  providing highlight capability

https://github.com/gohxs/readline 

Also corrected some issues and crashes as shown in my readline merge attempt
https://github.com/chzyer/readline/pull/130 
 
I think you can easily (not sure about multilines) implement  https://github.com/alecthomas/chroma the that for: 
> syntax highlighting (WIP)




As for completion I implemented it on mine as a regular PrefixCompleter from package readline but I started to implement a lexer/parser to contextual complete

> SQL completion (WIP)

I was also trying to do something with the history stored:

![output](https://user-images.githubusercontent.com/25049350/31327590-bb77cbba-aca6-11e7-8422-7c0433367519.gif)

**Comment by kenshaw** [comment] 2017-10-09 07:34
If the API is the same as the original `readline` package, it should be able to drop into `usql` without much difficultly. I already have a working branch of `usql` with some highlighting involved, but haven't finished it.

**Comment by hexasoftware** [comment] 2017-10-09 11:31
For the highlight i had to adapt readline itself, hence the fork, with the way readline is made(controlling the cursor, position the line, etc) i didn't found an easy solution outside of pkg itself. 

Although seems that the author started merging some PR's and one of those includes a similar to the one I adapted. so the latest readline should support something similar.

Odly he didn't merge my PR and went away, i've got a couple of user posted issues fixed
https://github.com/gohxs/readline/issues?q=is%3Aissue+is%3Aclosed

**Comment by kenshaw** [comment] 2017-10-09 17:51
I changed over to @hexasoftware 's `readline` package, as well as changed the github group, and implemented the initial version of the syntax highlighting.

Use `\set` to change the settings:
```sh
ken@ken-desktop:~$ go install github.com/xo/usql
ken@ken-desktop:~$ usql pg://
Connected with driver postgres (PostgreSQL 9.6.5)
WELCOME TO THE JUNGLE Tue Oct 10 00:51:06 WIB 2017
Type "help" for help.

pg:booktest@=> \set
SHOW_HOST_INFORMATION = 'true'
SYNTAX_HL = 'true'
SYNTAX_HL_FORMAT = 'terminal16m'
SYNTAX_HL_STYLE = 'monokai'
pg:booktest@=> \set SYNTAX_HL_STYLE dracula
```

**Closed by kenshaw** 2017-10-09 17:51 UTC

**Comment by kenshaw** [comment] 2017-10-16 02:02
Even though I closed this issue, wanted to give a brief update here. I've tracked down "most" of the bugs / issues with syntax highlighting. I'll be adding "completion" as soon as I can get to it. Appreciate @hexasoftware additions to `readline` -- originally I had been looking at making similar changes to `readline` in order to get `chroma` to work with it, but glad that I did not ultimately have to. The syntax highlighting is hackish, inefficient, and ugly, but hey, it works! Note though that for whatever reason it doesn't seem to work correctly on Windows. 

![screenshot from 2017-10-16 08-58-35](https://user-images.githubusercontent.com/2274859/31592129-3b2f9b7c-b250-11e7-8cf5-cd2a808ab40d.png)

I'll be doing a new release soon, after a couple of other features/enhancements, but please if you can, try this out with a couple of different databases, and let me know if there are any issues. You can simply do the standard Go installation:

```sh
$ go get -u github.com/xo/usql
```

**Comment by hexasoftware** [comment] 2017-10-16 10:41
chzyer/readline (thus gohxs/readline) has some issues with windows ansi, it should support at least 16colors

**Comment by dsh2** [comment] 2018-03-10 13:32
I am confused. According to the subject of this issue the issue is about completion, but people keep talking about syntax highlighting. Moreover, if I am not mistaken, there is no completion at all in usql, let alone context-based completion - contrary to what the main README.md says. That's disappointing.

**Comment by thorstenkampe** [comment] 2018-09-09 09:51
Can anyone confirm @dsh2 's claim? Tab-completion is much more useful than syntax highlighting. Without tab-completion `usql` would basically be a multi-database `Sqlcmd` replacement (feature-wise)

**Comment by Xdminsy** [comment] 2020-06-30 02:24
Well, I don't understand why README writes that `usql` supports tab completion.
There is no completion at all, pressing tab just inserts a tab. ( I only tried it on Windows & WSL)
I think even completion such as in phpMyAdmin is better than this, it seems in phpMyAdmin the completion is somewhat just a list of keywords without context.
A REPL without completion is I think much less useful.
