### ISSUE TITLE
Implement \G "vertical" output format like MySQL client

### ISSUE THREAD

**Issue by kolbe** [xo/usql#186] opened 2021-03-19 21:51 UTC
The MySQL client has a great "vertical format" if you use "\G" instead of "\g" or ";".

The benefit of this is that it's easy to get very long/wide output in a way that it can be easily copied in the terminal.

It's nice to be able to use `\G` on a single-statement instead of having to change the output format in a more persistent way.

```
mysql> show create table t3;
+-------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Table | Create Table                                                                                                                                                               |
+-------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| t3    | CREATE TABLE `t3` (
  `id` char(4) NOT NULL,
  `x` int(11) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `x` (`x`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin |
+-------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
1 row in set (0.001 sec)

mysql> show create table t3\G
*************************** 1. row ***************************
       Table: t3
Create Table: CREATE TABLE `t3` (
  `id` char(4) NOT NULL,
  `x` int(11) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `x` (`x`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin
1 row in set (0.001 sec)
```

**Comment by nineinchnick** [comment] 2021-03-20 11:08
There's `\x` that allows you to switch to a vertical format. If you don't want to make it permanent try `\x auto` which will automatically use vertical format if the output is too wide for the current terminal. This was recently added and is only available on the master branch, not in the latest release (0.8.2).

**Comment by kolbe** [comment] 2021-03-20 16:52
The recently-added "vertical" format doesn't really address the copy-paste use case.

```
ti:root@localhost:4000=> \x
Expanded display is on.
ti:root@localhost:4000=> show create table t4;

-[ RECORD 1 ]---------------------------------------------------------------
 Table        | t4
 Create Table | CREATE TABLE "t4" (                                        +
              |   "id" char(4) NOT NULL,                                   +
              |   "x" int(11) DEFAULT NULL,                                +
              |   PRIMARY KEY ("id"),                                      +
              |   KEY "x" ("x")                                            +
              | ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin

```

And in any case `\x auto` doesn't seem to trigger in this setting:

```
ti:root@localhost:4000=> \x auto
Expanded display is used automatically.
ti:root@localhost:4000=> show create table t4;

 Table |                        Create Table
-------+-------------------------------------------------------------
 t4    | CREATE TABLE "t4" (                                        +
       |   "id" char(4) NOT NULL,                                   +
       |   "x" int(11) DEFAULT NULL,                                +
       |   PRIMARY KEY ("id"),                                      +
       |   KEY "x" ("x")                                            +
       | ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin
(1 row)
```

**Comment by nineinchnick** [comment] 2021-03-20 17:21
We try to follow psql closely and I don't think there's a way to display newlines ignoring being inside a table cell. Can you try using other output formats, like csv? We recently also added asciidoc which should be human readable but allow you to achieve what you want. But it's also only on the master branch, not released yet.

**Comment by kenshaw** [comment] 2021-03-20 23:19
For what it's worth, I'm open to adding a `\G` metacommand. I of course do think we should try to be as close to `psql` as possible, but there's no reason we can't adopt some of MySQL's command line functionality as long as:

1) it's not a duplicate of existing functionality (I would even suggest that aliases would not be allowed, but since this is functionally different enough it's worth considering)
2) doesn't clash with behavior from `psql` -- since `psql` doesn't have a `\G`, I think this would be acceptable

Assuming the above, I think it would be OK to add this.

**Comment by nineinchnick** [comment] 2021-03-21 08:17
There's already `\g` (and `\gx`) implemented but without formatting options. `\G` could be an alias of `\gx` with a new option for tbmlfmt, something like `contain-newlines=false`.

**Comment by nineinchnick** [comment] 2021-03-26 17:17
`\G` could be an alias to `\gx (tuples_only=on)`

**Comment by kenshaw** [comment] 2021-04-04 02:54
I just pushed a commit that copies MySQL's `\G`. @kolbe please test and let me know if this works as expected.

Note: this deviates from MySQL in that `NULL` is shown as a blank string. This can be configured by setting the `\pset` `null` variable:

```sh
my:root@localhost/test=> \pset null 'NULL'
Null display is "NULL".
my:root@localhost/test=> select * from test \G
*************************** 1. row ***************************
a: yes
b: no
*************************** 2. row ***************************
a: three
b: NULL
*************************** 3. row ***************************
a: 1
b: 2
*************************** 4. row ***************************
a: 1
b: 2
*************************** 5. row ***************************
a: 1
b: 2
*************************** 6. row ***************************
a: 1
b: 2
*************************** 7. row ***************************
a: 1
b: 2
*************************** 8. row ***************************
a: 1
b: 2
*************************** 9. row ***************************
a: 1
b: 2
*************************** 10. row ***************************
a: 1
b: 2
*************************** 11. row ***************************
a: 1
b: 2
*************************** 12. row ***************************
a: 1
b: 2
*************************** 13. row ***************************
a: 1
b: 2
*************************** 14. row ***************************
a: 1
b: 2
*************************** 15. row ***************************
a: 1
b: 2
*************************** 16. row ***************************
a: 1
b: 2
*************************** 17. row ***************************
a: 1
b: 2
*************************** 18. row ***************************
a: 1
b: 2
*************************** 19. row ***************************
a: 1
b: 2
*************************** 20. row ***************************
a: 1
b: 2
*************************** 21. row ***************************
a: 1
b: 2
*************************** 22. row ***************************
a: 1
b: 2

my:root@localhost/test=>  
```

**Closed** 2021-04-04 02:56 UTC
